apiVersion: v1
kind: ReplicationController
metadata:
  name: todo-rc
spec:
  replicas: 2
  selector:
    app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo
          image: saiharshavarma28/todo-flask:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/tododb"
